### ISSUE TITLE
AttributeError: 'str' object has no attribute 'os'

### ISSUE THREAD

**Issue by lyc0221** [UpCloudLtd/upcloud-python-api#59]
```
        newserver = UpcloudServer(
            zone = zone,
            title = label,
            hostname = label,
            plan = plan,
            storage_devices = {
                'storage_device': [
                    {
                        "action": action,
                        "storage": storage,
                        "title": "windows from a template",
                        "size": 80,
                        "tier": "maxiops"
                    }
                ],
            }
        )
        data = self.upcloud.create_server(newserver)
```

Why do I need OS parameters? The official document did not mention

https://developers.upcloud.com/8-servers/#create-server

![image](https://user-images.githubusercontent.com/40416749/55394911-0aa9a200-5573-11e9-8fc3-98585589c3d9.png)

**Comment by elnygren** [comment]
`storage_devices` should be a list of `Storage` instances. eg:

```python
storage_devices = [
                Storage(os = "Ubuntu 14.04", size=10, tier=maxiops, title='The OS drive'),
                Storage(size=10),
]
```

---

**But what's this "os" thing?**

The `os` attribute of Storage is mainly used by the Server class https://github.com/UpCloudLtd/upcloud-python-api/blob/b283813bf2e79d441a3b1a5ed445e58a1c4c431a/upcloud_api/server.py#L295 at https://github.com/UpCloudLtd/upcloud-python-api/blob/b283813bf2e79d441a3b1a5ed445e58a1c4c431a/upcloud_api/server.py#L347 to select a storage template

However, when you're using `Storage` class, there is no nee to use `os`, it's only there for convenience as it's nicer to write `"Human Readable things"` rather than `uuidv4` strings :)


Note: you can also just use `requests` to send HTTP requests directly if you want to be closer to the JSON/http level of the API. See: https://github.com/UpCloudLtd/upcloud-python-api/blob/master/upcloud_api/cloud_manager/base.py#L21

**Comment by PopoSensei** [comment]
Hello from 2020. Hope elnygren answer helped in some way. I will now close this issue.
